apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikings-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vikings
  template:
    metadata:
      labels:
        app: vikings
    spec:
      containers:
        - name: vikings-container
          image: fares223/vikingsproject:v1.0
          ports:
            - containerPort: 3000
